_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.1
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.1
            "5": 0.19.1
            "6": 4.46.3
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
data_config:
    value:
        max_dist: 100
        max_neighbors: 12
        min_cell_count: 3
        min_gene_count: 200
        normalize_method: log1p
        use_pca: true
model_config:
    value:
        attention_probs_dropout_prob: 0.1
        hidden_dropout_prob: 0.1
        hidden_size: 768
        intermediate_size: 3072
        num_attention_heads: 12
        num_hidden_layers: 12
        use_cell_state: true
        use_gene_context: true
        use_spatial_context: true
training_config:
    value:
        batch_size: 16
        feature_weights:
            border_probability: 1
            cancer_score: 2
            cell_cycle_score: 1.5
            g2m_score: 1
            glycolysis_score: 1
            local_density: 1.5
            local_heterogeneity: 1.5
            mean_neighbor_expr: 1.5
            n_genes: 1
            oxidative_phos_score: 1
            pct_counts_mito: 1.5
            pct_counts_ribo: 1.5
            s_score: 1
            stress_score: 1.5
            total_counts: 1
        learning_rate: 0.0001
        loss_weights:
            cell_state: 1.5
            confidence: 0.5
            feature: 1
            gene_expression: 1
            neighbor: 1
            spatial_context: 1.5
        num_epochs: 10
        val_split: 0.2
